org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neo_version=21.1.219
neo_version_range=[21.1,)
loader_version_range=[4,)

parchment_minecraft_version=1.21
parchment_mappings_version=2024.07.28

mod_id=alexscavesexemplified
mod_name=Alex's Caves Exemplified
mod_license=MIT
mod_version=2.2.1
mod_group_id=org.crimsoncrips
mod_authors=The Crimson, Reimainder, Drullkus
mod_description=An addon that adds tons of new features specifically for Alex's Caves
